#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd

passwd_file="/etc/passwd"
while IFS= read -r username userid home_directory _
do
	echo "$username:$userid:$home_directory"
done < "$passwd_file"
