#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the i
#+ HTTP status code from the Apache log file

apache_log_file="apache-access.log"
awk -F ' ' '{print $1, $9}' $apache_log_file | sort | uniq -c|sort -nr
